# Generated by Django 2.1.2 on 2018-10-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20181023_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='Россия', help_text='Введите название страны (например: Россия, Канада, Украина)', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='location',
            field=models.CharField(default='Широта: 59°56′19″ с.ш. Долгота: 30°18′50″ в.д', help_text='Введите координаты города (например Широта: 59°56′19″ с.ш. Долгота: 30°18′50″ в.д)', max_length=25),
            preserve_default=False,
        ),
    ]
