# Generated by Django 2.1.2 on 2018-10-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20181024_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(blank=True, help_text='Введите название страны (например: Россия, Канада, Украина)', max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='location',
            field=models.CharField(blank=True, help_text='Введите координаты города (например: Широта: 59°56′19″ с.ш. Долгота: 30°18′50″ в.д)', max_length=25),
        ),
    ]
