# Generated by Django 2.1.2 on 2018-10-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20181024_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(help_text='Введите название страны (например: Россия, Канада, Украина)', max_length=30),
        ),
    ]
