# Generated by Django 2.1.2 on 2018-10-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20181024_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
