# Generated by Django 2.1.2 on 2018-11-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='cloudiness',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='description',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temperature_day',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temperature_max',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temperature_min',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temperature_night',
        ),
        migrations.AddField(
            model_name='weather',
            name='humidity',
            field=models.IntegerField(default=25, verbose_name='Cloudiness'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='icon',
            field=models.CharField(default='01n', max_length=4, verbose_name='Icon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='night',
            field=models.IntegerField(default=10, verbose_name='Temperature night'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='temp',
            field=models.IntegerField(default=10, verbose_name='Temperature'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind',
            field=models.IntegerField(verbose_name='Wind'),
        ),
    ]
