# Generated by Django 2.1.2 on 2018-11-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_auto_20181107_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.DateField(verbose_name='Time'),
        ),
    ]
