# Generated by Django 2.1.2 on 2018-11-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_auto_20181107_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.IntegerField(verbose_name='Time'),
        ),
    ]
