# Generated by Django 2.1.2 on 2018-11-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0013_auto_20181107_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='time',
        ),
    ]
