# Generated by Django 2.1.2 on 2018-11-07 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0014_remove_weather_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time'),
            preserve_default=False,
        ),
    ]
