# Generated by Django 2.1.2 on 2018-11-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0015_weather_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='direction',
            field=models.CharField(default=135, max_length=8, verbose_name='Direction of wind'),
            preserve_default=False,
        ),
    ]
